apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
spec:
  containers:
  - name: volume-pod
    image: busybox
    command: ["/bin/sh", "-c", "echo cka > /opt/course.txt && sleep 100s"]
    volumeMounts:
    - name: data
      mountPath: /opt
  restartPolicy: Never
  volumes:
    - name: data
      emptyDir: {}