apiVersion: v1
kind: Pod
metadata:
  name: tolerations-pod
spec:
  tolerations:
  - key: app
    value: ssd
    operator: Equal
    effect: NoSchedule
  containers:
  - name: tolerations-pod
    image: nginx