apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pregunta5
spec:
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /datos
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pregunta5
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi