apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pregunta2
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /pregunta2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pregunta2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-pregunta2
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: data-volume
      mountPath: /pregunta2
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: pvc-pregunta2