apiVersion: v1
kind: Pod
metadata:
  name: init-pod
spec:
  initContainers:
  - name: init-container
    image: busybox:1.28
    command: ['sh', '-c', 'sleep 10']
  containers:
  - name: container
    image: nginx
