apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
  labels:
    app: multi-pod
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort:  80
      name:  http
  - name: logging-sidecar
    image: fluent/fluent-bit:latest