apiVersion: v1
kind: Pod
metadata:
  name: toleration-pod
  labels:
    env: prod
spec:
  tolerations: 
  - key: "dedicated" 
    operator: "Exists"
    effect: "NoSchedule"
  containers:
  - name: toleration-pod
    image: nginx