apiVersion: v1
kind: Pod
metadata:
  name: affinity-pod
spec:
  containers:
  - name: affinity-pod
    image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: hardware
            operator: In
            values:
            - gpu